# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: medical_portal_development

test:
  <<: *default
  database: medical_portal_test

production:
  <<: *default
  database: medical_portal_production
  username: medical_portal
  password: <%= ENV['MEDICAL_PORTAL_DATABASE_PASSWORD'] %>